---
- name: Deploy the requested number of AWS EC2 instances
  hosts: localhost
  connection: locali
  vars_prompt:
  - name: "number_of_instances"
    prompt: "How many EC2 instances would you like to create?"
    default: 1
  tasks:
    - name: provision a single ec2 instance
      ec2:
        key_name: dev-network
        instance_type: t2.micro
        image: ami-9887c6e7
        group: kikicloud-public
        wait: true
        count: "{{ number_of_instances }}"
        vpc_subnet_id: subnet-0ade37adde413715a
        assign_public_ip: yes
        aws_access_key: "{{ lookup('env','AWS_ACCESS_KEY_ID') }}"
        aws_secret_key: "{{ lookup('env','AWS_SECRET_ACCESS_KEY') }}"
        region: us-east-1
        instance_tags:
          Name: Webserver #"{{ nametag }}"
          Env: Dev
          Learning: True
          OS: CentOS
      register: ec2
    - name: Hold on a darn second for those instances to get tagged
      pause:
        minutes: 1
